require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Reportings::B1sController do

  # This should return the minimal set of attributes required to create a valid
  # Reportings::B1. As you add validations to Reportings::B1, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Reportings::B1sController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all reportings_b1s as @reportings_b1s" do
      b1 = Reportings::B1.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reportings_b1s).should eq([b1])
    end
  end

  describe "GET show" do
    it "assigns the requested b1 as @b1" do
      b1 = Reportings::B1.create! valid_attributes
      get :show, {:id => b1.to_param}, valid_session
      assigns(:b1).should eq(b1)
    end
  end

  describe "GET new" do
    it "assigns a new b1 as @b1" do
      get :new, {}, valid_session
      assigns(:b1).should be_a_new(Reportings::B1)
    end
  end

  describe "GET edit" do
    it "assigns the requested b1 as @b1" do
      b1 = Reportings::B1.create! valid_attributes
      get :edit, {:id => b1.to_param}, valid_session
      assigns(:b1).should eq(b1)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Reportings::B1" do
        expect {
          post :create, {:b1 => valid_attributes}, valid_session
        }.to change(Reportings::B1, :count).by(1)
      end

      it "assigns a newly created b1 as @b1" do
        post :create, {:b1 => valid_attributes}, valid_session
        assigns(:b1).should be_a(Reportings::B1)
        assigns(:b1).should be_persisted
      end

      it "redirects to the created b1" do
        post :create, {:b1 => valid_attributes}, valid_session
        response.should redirect_to(Reportings::B1.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved b1 as @b1" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reportings::B1.any_instance.stub(:save).and_return(false)
        post :create, {:b1 => {}}, valid_session
        assigns(:b1).should be_a_new(Reportings::B1)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reportings::B1.any_instance.stub(:save).and_return(false)
        post :create, {:b1 => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested b1" do
        b1 = Reportings::B1.create! valid_attributes
        # Assuming there are no other reportings_b1s in the database, this
        # specifies that the Reportings::B1 created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Reportings::B1.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => b1.to_param, :b1 => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested b1 as @b1" do
        b1 = Reportings::B1.create! valid_attributes
        put :update, {:id => b1.to_param, :b1 => valid_attributes}, valid_session
        assigns(:b1).should eq(b1)
      end

      it "redirects to the b1" do
        b1 = Reportings::B1.create! valid_attributes
        put :update, {:id => b1.to_param, :b1 => valid_attributes}, valid_session
        response.should redirect_to(b1)
      end
    end

    describe "with invalid params" do
      it "assigns the b1 as @b1" do
        b1 = Reportings::B1.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reportings::B1.any_instance.stub(:save).and_return(false)
        put :update, {:id => b1.to_param, :b1 => {}}, valid_session
        assigns(:b1).should eq(b1)
      end

      it "re-renders the 'edit' template" do
        b1 = Reportings::B1.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reportings::B1.any_instance.stub(:save).and_return(false)
        put :update, {:id => b1.to_param, :b1 => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested b1" do
      b1 = Reportings::B1.create! valid_attributes
      expect {
        delete :destroy, {:id => b1.to_param}, valid_session
      }.to change(Reportings::B1, :count).by(-1)
    end

    it "redirects to the reportings_b1s list" do
      b1 = Reportings::B1.create! valid_attributes
      delete :destroy, {:id => b1.to_param}, valid_session
      response.should redirect_to(reportings_b1s_url)
    end
  end

end
