require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Reportings::PlansController do

  # This should return the minimal set of attributes required to create a valid
  # Reportings::Plan. As you add validations to Reportings::Plan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Reportings::PlansController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all reportings_plans as @reportings_plans" do
      plan = Reportings::Plan.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reportings_plans).should eq([plan])
    end
  end

  describe "GET show" do
    it "assigns the requested reportings_plan as @reportings_plan" do
      plan = Reportings::Plan.create! valid_attributes
      get :show, {:id => plan.to_param}, valid_session
      assigns(:reportings_plan).should eq(plan)
    end
  end

  describe "GET new" do
    it "assigns a new reportings_plan as @reportings_plan" do
      get :new, {}, valid_session
      assigns(:reportings_plan).should be_a_new(Reportings::Plan)
    end
  end

  describe "GET edit" do
    it "assigns the requested reportings_plan as @reportings_plan" do
      plan = Reportings::Plan.create! valid_attributes
      get :edit, {:id => plan.to_param}, valid_session
      assigns(:reportings_plan).should eq(plan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Reportings::Plan" do
        expect {
          post :create, {:reportings_plan => valid_attributes}, valid_session
        }.to change(Reportings::Plan, :count).by(1)
      end

      it "assigns a newly created reportings_plan as @reportings_plan" do
        post :create, {:reportings_plan => valid_attributes}, valid_session
        assigns(:reportings_plan).should be_a(Reportings::Plan)
        assigns(:reportings_plan).should be_persisted
      end

      it "redirects to the created reportings_plan" do
        post :create, {:reportings_plan => valid_attributes}, valid_session
        response.should redirect_to(Reportings::Plan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reportings_plan as @reportings_plan" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reportings::Plan.any_instance.stub(:save).and_return(false)
        post :create, {:reportings_plan => {}}, valid_session
        assigns(:reportings_plan).should be_a_new(Reportings::Plan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reportings::Plan.any_instance.stub(:save).and_return(false)
        post :create, {:reportings_plan => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reportings_plan" do
        plan = Reportings::Plan.create! valid_attributes
        # Assuming there are no other reportings_plans in the database, this
        # specifies that the Reportings::Plan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Reportings::Plan.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => plan.to_param, :reportings_plan => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested reportings_plan as @reportings_plan" do
        plan = Reportings::Plan.create! valid_attributes
        put :update, {:id => plan.to_param, :reportings_plan => valid_attributes}, valid_session
        assigns(:reportings_plan).should eq(plan)
      end

      it "redirects to the reportings_plan" do
        plan = Reportings::Plan.create! valid_attributes
        put :update, {:id => plan.to_param, :reportings_plan => valid_attributes}, valid_session
        response.should redirect_to(plan)
      end
    end

    describe "with invalid params" do
      it "assigns the reportings_plan as @reportings_plan" do
        plan = Reportings::Plan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reportings::Plan.any_instance.stub(:save).and_return(false)
        put :update, {:id => plan.to_param, :reportings_plan => {}}, valid_session
        assigns(:reportings_plan).should eq(plan)
      end

      it "re-renders the 'edit' template" do
        plan = Reportings::Plan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reportings::Plan.any_instance.stub(:save).and_return(false)
        put :update, {:id => plan.to_param, :reportings_plan => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reportings_plan" do
      plan = Reportings::Plan.create! valid_attributes
      expect {
        delete :destroy, {:id => plan.to_param}, valid_session
      }.to change(Reportings::Plan, :count).by(-1)
    end

    it "redirects to the reportings_plans list" do
      plan = Reportings::Plan.create! valid_attributes
      delete :destroy, {:id => plan.to_param}, valid_session
      response.should redirect_to(reportings_plans_url)
    end
  end

end
