require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReportingForms::LaborLinesController do

  # This should return the minimal set of attributes required to create a valid
  # ReportingForms::LaborLine. As you add validations to ReportingForms::LaborLine, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReportingForms::LaborLinesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all reporting_forms_labor_lines as @reporting_forms_labor_lines" do
      labor_line = ReportingForms::LaborLine.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reporting_forms_labor_lines).should eq([labor_line])
    end
  end

  describe "GET show" do
    it "assigns the requested reporting_forms_labor_line as @reporting_forms_labor_line" do
      labor_line = ReportingForms::LaborLine.create! valid_attributes
      get :show, {:id => labor_line.to_param}, valid_session
      assigns(:reporting_forms_labor_line).should eq(labor_line)
    end
  end

  describe "GET new" do
    it "assigns a new reporting_forms_labor_line as @reporting_forms_labor_line" do
      get :new, {}, valid_session
      assigns(:reporting_forms_labor_line).should be_a_new(ReportingForms::LaborLine)
    end
  end

  describe "GET edit" do
    it "assigns the requested reporting_forms_labor_line as @reporting_forms_labor_line" do
      labor_line = ReportingForms::LaborLine.create! valid_attributes
      get :edit, {:id => labor_line.to_param}, valid_session
      assigns(:reporting_forms_labor_line).should eq(labor_line)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ReportingForms::LaborLine" do
        expect {
          post :create, {:reporting_forms_labor_line => valid_attributes}, valid_session
        }.to change(ReportingForms::LaborLine, :count).by(1)
      end

      it "assigns a newly created reporting_forms_labor_line as @reporting_forms_labor_line" do
        post :create, {:reporting_forms_labor_line => valid_attributes}, valid_session
        assigns(:reporting_forms_labor_line).should be_a(ReportingForms::LaborLine)
        assigns(:reporting_forms_labor_line).should be_persisted
      end

      it "redirects to the created reporting_forms_labor_line" do
        post :create, {:reporting_forms_labor_line => valid_attributes}, valid_session
        response.should redirect_to(ReportingForms::LaborLine.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reporting_forms_labor_line as @reporting_forms_labor_line" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReportingForms::LaborLine.any_instance.stub(:save).and_return(false)
        post :create, {:reporting_forms_labor_line => {}}, valid_session
        assigns(:reporting_forms_labor_line).should be_a_new(ReportingForms::LaborLine)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReportingForms::LaborLine.any_instance.stub(:save).and_return(false)
        post :create, {:reporting_forms_labor_line => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reporting_forms_labor_line" do
        labor_line = ReportingForms::LaborLine.create! valid_attributes
        # Assuming there are no other reporting_forms_labor_lines in the database, this
        # specifies that the ReportingForms::LaborLine created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ReportingForms::LaborLine.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => labor_line.to_param, :reporting_forms_labor_line => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested reporting_forms_labor_line as @reporting_forms_labor_line" do
        labor_line = ReportingForms::LaborLine.create! valid_attributes
        put :update, {:id => labor_line.to_param, :reporting_forms_labor_line => valid_attributes}, valid_session
        assigns(:reporting_forms_labor_line).should eq(labor_line)
      end

      it "redirects to the reporting_forms_labor_line" do
        labor_line = ReportingForms::LaborLine.create! valid_attributes
        put :update, {:id => labor_line.to_param, :reporting_forms_labor_line => valid_attributes}, valid_session
        response.should redirect_to(labor_line)
      end
    end

    describe "with invalid params" do
      it "assigns the reporting_forms_labor_line as @reporting_forms_labor_line" do
        labor_line = ReportingForms::LaborLine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReportingForms::LaborLine.any_instance.stub(:save).and_return(false)
        put :update, {:id => labor_line.to_param, :reporting_forms_labor_line => {}}, valid_session
        assigns(:reporting_forms_labor_line).should eq(labor_line)
      end

      it "re-renders the 'edit' template" do
        labor_line = ReportingForms::LaborLine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReportingForms::LaborLine.any_instance.stub(:save).and_return(false)
        put :update, {:id => labor_line.to_param, :reporting_forms_labor_line => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reporting_forms_labor_line" do
      labor_line = ReportingForms::LaborLine.create! valid_attributes
      expect {
        delete :destroy, {:id => labor_line.to_param}, valid_session
      }.to change(ReportingForms::LaborLine, :count).by(-1)
    end

    it "redirects to the reporting_forms_labor_lines list" do
      labor_line = ReportingForms::LaborLine.create! valid_attributes
      delete :destroy, {:id => labor_line.to_param}, valid_session
      response.should redirect_to(reporting_forms_labor_lines_url)
    end
  end

end
